### ISSUE TITLE
Question: distribution of '__generate_random'

### ISSUE THREAD

**Issue by schutm** [marcoonroad/ocaml-cuid#7]
Hi,

please take into account I'm by far no crypto-expert, so please bear with me.

I understand the lines https://github.com/marcoonroad/ocaml-cuid/blob/f812a47f32949e038207e5d344bcb6a3da16eb4b/lib/cuid.ml#L93-L96 (and summation of 9 bytes) is to prevent a (slight) bias to 0, 1, 2 or 3.

However if I look at line https://github.com/marcoonroad/ocaml-cuid/blob/f812a47f32949e038207e5d344bcb6a3da16eb4b/lib/cuid.ml#L97 I'd think this also introduces a bias. Since a * b * c * d is the same as b * c * a * d (or whatever order you put them in) it looks to me the distribution is not fair. E.G. the MSB of the 1st byte is only set if a = b = c = d = 36, while the MSB of the second byte can be set in several different ways, where it doesn't matter whether which of a, b, c or d gets assigned a certain value (as long as the required values are assigned to the variable, but it doesn't matter to which variable the result will be the asme). However if we do (36 ^ 0) * a + (36 ^ 1) * b + (36 ^ 2) * c + (36 ^ 3) * d  the MSB being set is directly dependent on the result of the crypto function. As a result the distribution should be fair in my opinion.

Any comments? Where is my reasoning going off?

**Comment by marcoonroad** [comment]
Hi @schutm ,
Sorry for the late reply.
You are right, the original/older version is prone to leading zeroes on left and more bytes likely filled on right. While it is not a randomness problem itself (the number distribution is still uniform 'cause the input is assumed to be random), for cryptographic utilities using `xor`, it could expose the part of the other data being "xored".
